language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55/cmake-3.x
    packages:
      - g++-6
      - cmake

script:
 - mkdir build
 - cd build
 - cmake --version
 - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-6 ../source
 - make
