language: cpp

os: linux
dist: focal

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-11
      
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-11 ../source
 - make
