language: cpp

os: linux
dist: focal

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install g++-11
      
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-11 ../source
 - make
