sprout
======


== Brief

sprout is a simple raytracer written in C++. I work on it in my spare time with the goal to learn about physically based rendering and global illumination and, first of all, to have fun.

The overall architecture is heavily inspired by PBRT while the implementation details differ more or less strongly in most places.

At the moment the most advanced integrator is a uni-directional path tracer with forward prediction and multiple importance sampling. Area lights and HDRI lights are supported. The default material is a combination of qualitative Oren-Nayar and GGX. There is supprt for a few built in shapes (sphere, disk, place) as well as triangle meshes.

A render is configurable by various json files that describe the various parts of the scene (shapes, lights, materials etc.).

== Installation

== Dependencies

I try to keep the dependencies reasonably low in this project. At the moment there are three of them. They are all included in the repository and should not give any trouble.

.Dependencies
. Miniz for encoding/decoding PNG images and readin gz archives
. RapidJSON for parsin json files
. TCLAP for parsing command line arguments

