include("${CMAKE_CURRENT_LIST_DIR}/bvh/triangle_bvh.cmake")

target_sources(core
	PRIVATE
	"${CMAKE_CURRENT_LIST_DIR}/triangle_intersection.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_json_handler.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_json_handler.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_mesh_exporter.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_mesh_exporter.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_mesh_generator.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_mesh_provider.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_mesh_provider.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_mesh.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_mesh.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_morph_target_collection.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_morph_target_collection.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_morphable_mesh.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_morphable_mesh.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_primitive_mt.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_primitive_mt.inl"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_primitive.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/triangle_type.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/vertex_encoding.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/vertex_encoding.inl"
	"${CMAKE_CURRENT_LIST_DIR}/vertex_layout_description.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/vertex_layout_description.hpp"
	)  
