target_sources(cli
  PRIVATE
  "${CMAKE_CURRENT_LIST_DIR}/client.cpp"
  "${CMAKE_CURRENT_LIST_DIR}/client.hpp"
  "${CMAKE_CURRENT_LIST_DIR}/message_handler.hpp"
  "${CMAKE_CURRENT_LIST_DIR}/server.cpp"
  "${CMAKE_CURRENT_LIST_DIR}/server.hpp"
  "${CMAKE_CURRENT_LIST_DIR}/websocket.cpp"
  "${CMAKE_CURRENT_LIST_DIR}/websocket.hpp"
) 
