add_library(base "") 

target_include_directories(base PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_LIST_DIR}>)
target_include_directories(base PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_LIST_DIR}/../../thirdparty/include/>)

include("${CMAKE_CURRENT_LIST_DIR}/atomic/atomic.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/chrono/chrono.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/crypto/crypto.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/debug/debug.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/encoding/encoding.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/flags/flags.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/json/json.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/math/math.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/memory/memory.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/net/net.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/platform/platform.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/random/random.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/simd/simd.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/spectrum/spectrum.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/string/string.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/thread/thread.cmake")
