target_sources(core
    PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/emittance.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/emittance.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/light.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/light.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/null_light.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/null_light.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/prop_image_light.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/prop_image_light.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/prop_light.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/prop_light.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/prop_volume_light.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/prop_volume_light.hpp"
    ) 
