target_sources(base
    PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/distribution_1d.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/distribution_1d.inl"
	"${CMAKE_CURRENT_LIST_DIR}/distribution_2d.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/distribution_2d.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/distribution_3d.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/distribution_3d.hpp"
    )
