target_sources(core
	PRIVATE
	"${CMAKE_CURRENT_LIST_DIR}/testing_cdf.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/testing_cdf.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/testing_simd.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/testing_simd.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/testing_size.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/testing_size.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/testing_spectrum.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/testing_spectrum.hpp"
	)     
