target_sources(core
  PRIVATE
  "${CMAKE_CURRENT_LIST_DIR}/exporting_sink_ffmpeg.cpp"
  "${CMAKE_CURRENT_LIST_DIR}/exporting_sink_ffmpeg.hpp"
  "${CMAKE_CURRENT_LIST_DIR}/exporting_sink_image_sequence.cpp"
  "${CMAKE_CURRENT_LIST_DIR}/exporting_sink_image_sequence.hpp"
  "${CMAKE_CURRENT_LIST_DIR}/exporting_sink_null.cpp"
  "${CMAKE_CURRENT_LIST_DIR}/exporting_sink_null.hpp"
  "${CMAKE_CURRENT_LIST_DIR}/exporting_sink_statistics.cpp"
  "${CMAKE_CURRENT_LIST_DIR}/exporting_sink_statistics.hpp"
  "${CMAKE_CURRENT_LIST_DIR}/exporting_sink.hpp"
)
