target_sources(core
	PRIVATE
	"${CMAKE_CURRENT_LIST_DIR}/scripting.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/scripting.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/scripting_engine.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/scripting_engine.hpp"
	"${CMAKE_CURRENT_LIST_DIR}/scripting_print.cpp"
	"${CMAKE_CURRENT_LIST_DIR}/scripting_print.hpp"
	)     
