target_sources(core
    PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/photon_grid.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/photon_grid.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/photon_importance.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/photon_importance.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/photon_map.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/photon_map.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/photon_mapper.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/photon_mapper.cpp"
    ) 
