include("${CMAKE_CURRENT_LIST_DIR}/aurora/aurora.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/flame/flame.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/fluid/fluid.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/mesh/mesh.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/sky/sky.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/starburst/starburst.cmake")
