target_sources(base
    PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/align.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/align.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/bitfield.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/bitfield.inl"
    "${CMAKE_CURRENT_LIST_DIR}/const.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/tiled_array.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/tiled_array.inl"
    "${CMAKE_CURRENT_LIST_DIR}/variant_map.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/variant_map.hpp"
    "${CMAKE_CURRENT_LIST_DIR}/variant_map.inl"
    )
